version: "3.8"

services:
  nodejs:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: "nodejs"
    ports:
      - "3000:3000"
    volumes:
      - ./:/mnt
    tty: true
    working_dir: /mnt/src
